configuracion CD/CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,15 +10,15 @@ jobs:
     steps:
       - name: Clonar el repositorio
         uses: actions/checkout@v4
-      - name: Verificar existencia de archivos base
+      - name: Verificar existencia de archivos
         run: |
-          if [ ! -f home.html ]; then echo 'Error: Falta home.html'; exit 1; fi
-          if [ ! -f styles.css ]; then echo 'Error: Falta styles.css'; exit 1; fi
-          echo 'Archivos verificados correctamente ✅'
+          if [ ! -f home.html ]; echo 'Error: Falta home.html'; exit 1; fi
+          if [ ! -f styles.css ]; echo 'Error: Falta styles.css'; exit 1; fi
+          echo 'Archivos verificados correctamente'
 
   deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Simular despliegue
-        run: echo 'Artefactos listos para el despliegue en el entorno de Staging 🚀'
+        run: echo 'listos para el despliegue'
